# Generated by Django 2.2 on 2021-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210123_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
